package com.lingshu.ai.core.model.task;

import java.time.LocalDateTime;
import java.util.List;

/**
 * The execution plan for a single {@link com.lingshu.ai.infrastructure.entity.TaskRun}.
 * Generated by the {@link com.lingshu.ai.core.service.TaskPlanner} and stored in
 * the task run's {@code runtime_snapshot_json} so the engine and frontend can
 * inspect it.
 *
 * @param steps       ordered list of steps to execute
 * @param summary     one-line description of the detected intent
 * @param intentLabel symbolic label for the intent category (e.g. "build", "fix")
 * @param createdAt   when the plan was generated
 */
public record TaskPlan(
        List<PlanStep> steps,
        String summary,
        String intentLabel,
        LocalDateTime createdAt
) {
    public static final String SNAPSHOT_KEY = "taskPlan";

    public TaskPlan {
        steps = steps == null ? List.of() : List.copyOf(steps);
    }

    public int stepCount() {
        return steps.size();
    }
}
